---
- name: Restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Restart dnf_timer
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: restarted
  become: true

- name: Reload_fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
