---
- name: Check if sshd daemon is running
  ansible.builtin.service:
    name: sshd
    state: started
- name: Set permissions to read-only accordingly
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '0600'
  become: true
- name: Set read permissions to keys accordingly
  ansible.builtin.shell:
    cmd: "chmod 0600 /etc/ssh/ssh_host_*_key"
  become: true
- name: Set read-write permissions to public keys accordingly
  ansible.builtin.shell:
    cmd: "chmod 0644 /etc/ssh/ssh_host_*_key.pub"
  become: true
- name: Hardening sshd_config file
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.parameter }}"
    line: "{{ item.line }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ sshd_options }}"
  notify: restart_sshd
  become: true
- name: Use only FIPS 140-2 compliant ciphers & algorithms
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    insertafter: "{{ item.regex }}"
    create: yes
  loop: "{{ fips140 }}"
  become: yes
