---
# Provisioning of server
- name: Start task provisioning
  ansible.builtin.include_tasks:
    file: provisioning.yml

# SSHD hardening
- name: Start task sshd hardening
  ansible.builtin.include_tasks:
    file: sshd.yml

# Add firewall and other security configurations
- name: Start task security
  ansible.builtin.include_tasks:
    file: security.yml
