---
- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  register: reboot

- name: Install important packages
  ansible.builtin.dnf:
    name: "{{ packages_list }}"
    state: present

- name: Create local user
  ansible.builtin.user:
    name: "{{ user }}"
    expires: "{{ user_expire_date }}"
    password: "{{ user_password }}"
    update_password: on_create
    groups: adm

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Reboot system
  ansible.builtin.reboot:
    msg: "Rebooting machine in 5 seconds"
  when: reboot.changed
