---
# Configure dnf automatic timer
- name: Start and enable dnf-automatic timer
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: started
    enabled: true

- name: Configure dnf-automatic timer config file
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.dnf_timer_parameter }}"
    line: "{{ item.dnf_timer_line }}"
  loop: "{{ dnf_timer_options }}"
  notify: Restart dnf_timer

- name: Configure dnf-automatic timer systemd unit file
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/dnf-automatic.timer
    regexp: "{{ dnf_systemd_unit_parameter }}"
    line: "{{ dnf_systemd_unit_line }}"
  notify: Restart dnf_timer

- name: Configure dnf-automatic timer systemd unit file
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/dnf-automatic.timer
    state: absent
    regexp: "^RandomizedDelaySec="
  notify: Restart dnf_timer

# Configure firewalld
- name: Install firewall
  ansible.builtin.dnf:
    name: firewalld

- name: Enable & start the firewall
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Port configuration
  ansible.posix.firewalld:
    port: 2200/tcp
    state: enabled
    permanent: true
    immediate: true

# Install and configure fail2ban
- name: Install & configure fail2ban
  block:
    - name: Install fail2ban
      ansible.builtin.dnf:
        name:
          - fail2ban
          - fail2ban-firewalld
        state: present
    - name: Copy jail custom configuration file into place.
      ansible.builtin.template:
        src: "{{ security_fail2ban_jail_template }}"
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "0644"
      notify:
        - Reload_fail2ban
    - name: Be sure fail2ban is always started and enabled
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: true
