---
# Configure firewalld
- name: Install firewall
  ansible.builtin.dnf:
    name: firewalld

- name: Enable & start the firewall
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Port configuration
  ansible.posix.firewalld:
    port: 2200/tcp
    state: enabled
    permanent: true
    immediate: true

# Configure CrowdSec
- name: Configure Crowdsec standard repository
  ansible.builtin.yum_repository:
    name: crowdsec
    description: CrowdSec Security
    state: present
    baseurl: https://packagecloud.io/crowdsec/crowdsec/el/9/$basearch
    gpgcheck: true
    gpgkey: "{{ item }}"
  loop: "{{ crowdsec_gpg_keys }}"

- name: Configure Crowdsec source repository
  ansible.builtin.yum_repository:
    name: crowdsec_source
    description: CrowdSec Security
    state: present
    baseurl: https://packagecloud.io/crowdsec/crowdsec/el/9/SRPMS
    gpgcheck: true
    gpgkey: "{{ item }}"
  loop: "{{ crowdsec_gpg_keys }}"

- name: Install Crowdsec
  ansible.builtin.dnf:
    name: 
    - crowdsec
    - crowdsec-firewall-bouncer-nftables
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
