---
- name: Check if sshd daemon is running
  ansible.builtin.service:
    name: sshd
    state: started
- name: Set permissions to read-only accordingly
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '0600'
- name: Set permissions to keys accordingly
  ansible.builtin.shell:
    cmd: "{{ item }}"
  loop:
    - "chmod 0600 /etc/ssh/ssh_host_*_key"
    - "chmod 0644 /etc/ssh/ssh_host_*_key.pub"
  register: result
  changed_when: result.rc != 0
- name: Allow sshd to listen on tcp port 2200
  community.general.seport:
    ports: 2200
    proto: tcp
    setype: ssh_port_t
    state: present
  when: ansible_facts['os_family'] == "RedHat"
- name: Hardening sshd_config file
  ansible.builtin.template:
    src: "{{ sshd_config_template }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Restart_sshd
